In [2]:
# import neessary libraries
import pandas as pd
from pyampute.exploration.mcar_statistical_tests import MCARTest

In [3]:
# load data
df_satellite_to_append = []
df_solar_to_append = []
df_wind_to_append = []

for farm in [1, 2, 3, 4, 5]:
    satellite_to_append = pd.read_csv(f"data/solar/enlitia_satellite_{farm}_data.csv")
    solar_to_append = pd.read_csv(f"data/solar/enlitia_solar_farm_{farm}_data.csv")
    wind_to_append = pd.read_csv(f"data/wind/enlitia_wind_farm_{farm}_data.csv")
    
    df_satellite_to_append.append(satellite_to_append)
    df_solar_to_append.append(solar_to_append)
    df_wind_to_append.append(wind_to_append)

df_satellite = pd.concat(df_satellite_to_append, ignore_index=True)
df_solar = pd.concat(df_solar_to_append, ignore_index=True)
df_wind = pd.concat(df_wind_to_append, ignore_index=True)

print("Satellite DataFrame:\n", df_satellite)
print("Solar DataFrame:\n", df_solar)
print("Wind DataFrame:\n", df_wind)

Satellite DataFrame:
         satellite_id              read_at  global_tilted_irradiance  \
0                  1  2022-01-01 00:00:00                       0.0
1                  1  2022-01-01 00:10:00                       0.0
2                  1  2022-01-01 00:20:00                       0.0
3                  1  2022-01-01 00:30:00                       0.0
4                  1  2022-01-01 00:40:00                       0.0
...              ...                  ...                       ...
476007             5  2024-01-09 14:00:00                     119.0
476008             5  2024-01-09 14:10:00                     121.0
476009             5  2024-01-09 14:20:00                      82.0
476010             5  2024-01-09 14:30:00                      49.0
476011             5  2024-01-09 14:40:00                      21.0

        global_horizontal_irradiance  temperature  cloud_cover
0                                0.0         13.0          1.4
1                                0.0         12.9          2.8
2                                0.0         12.9          2.8
3                                0.0         12.9          1.4
4                                0.0         12.8          6.6
...                              ...          ...          ...
476007                         124.0         12.0         68.0
476008                         125.0         12.0         67.0
476009                          85.0         12.0         76.0
476010                          51.0         13.0         85.0
476011                          22.0         13.0         93.0

[476012 rows x 6 columns]
Solar DataFrame:
          asset_id              read_at  ac_power  ac_voltage  ac_current  \
0              11  2022-01-01 07:40:00       0.0       4.000      0.0000
1              11  2022-01-01 07:50:00       9.0     232.000      0.1090
2              11  2022-01-01 08:00:00      57.0     233.000      0.2690
3              11  2022-01-01 08:10:00      82.0     235.000      0.2980
4              11  2022-01-01 08:20:00     224.0     235.000      0.5920
...           ...                  ...       ...         ...         ...
4081769       514  2024-01-09 14:15:00   13840.0     233.567     19.7977
4081770       514  2024-01-09 14:20:00   15976.0     234.600     22.8807
4081771       514  2024-01-09 14:25:00   22599.0     234.600     32.2090
4081772       514  2024-01-09 14:30:00   27227.0     234.767     38.9630
4081773       514  2024-01-09 14:35:00   28260.0     235.467     40.2160

            dc_power  dc_voltage  dc_current
0            0.00000     2.73333      0.0000
1            8.14973   214.46700      0.0380
2           43.55100   268.83300      0.1620
3           60.62470   275.56700      0.2200
4          157.13400   301.60000      0.5210
...              ...         ...         ...
4081769  13972.10000   531.02000      1.0925
4081770  16179.70000   534.48000      1.2580
4081771  23010.60000   538.22000      1.7745
4081772  27794.50000   541.86000      2.1300
4081773  28819.20000   537.64000      2.2240

[4081774 rows x 8 columns]
Wind DataFrame:
          asset_id              read_at  wind_speed  wind_direction  \
0              11  2021-01-01 00:00:00         8.3           296.0
1              11  2021-01-01 00:10:00         8.9           306.0
2              11  2021-01-01 00:20:00         8.1           298.0
3              11  2021-01-01 00:30:00         7.9           298.0
4              11  2021-01-01 00:40:00         8.1           296.0
...           ...                  ...         ...             ...
8367754       512  2023-03-30 09:50:00        10.7           224.0
8367755       512  2023-03-30 10:00:00         9.7           224.0
8367756       512  2023-03-30 10:10:00         9.2           224.0
8367757       512  2023-03-30 10:20:00         7.3           224.0
8367758       512  2023-03-30 10:30:00         7.4           233.0

         power_average  rotation_average  exterior_temperature  \
0               802.00             15.51                  -2.0
1               832.00             15.74                  -2.0
2               666.00             14.88                  -2.0
3               541.00             14.03                  -2.0
4               625.00             14.64                  -2.0
...                ...               ...                   ...
8367754        1984.49             13.93                  11.8
8367755        1826.37             13.95                  12.2
8367756        1567.75             13.74                  12.2
8367757         816.03             12.25                  12.5
8367758         861.56             12.49                  12.6

         nacelle_temperature
0                        9.0
1                        9.0
2                       10.0
3                       10.0
4                       10.0
...                      ...
8367754                 16.1
8367755                 16.6
8367756                 17.4
8367757                 17.5
8367758                 16.7

[8367759 rows x 8 columns]

In [4]:
dfs_dict = {
    "Satellite" : df_satellite,
    "Solar": df_solar,
    "Wind" : df_wind
}

for key, value in dfs_dict.items():
    print(f"Information of {key} df")
    print(value.info(),"\n")

Information of Satellite df
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 476012 entries, 0 to 476011
Data columns (total 6 columns):
 #   Column                        Non-Null Count   Dtype
---  ------                        --------------   -----
 0   satellite_id                  476012 non-null  int64
 1   read_at                       476012 non-null  object
 2   global_tilted_irradiance      476012 non-null  float64
 3   global_horizontal_irradiance  476012 non-null  float64
 4   temperature                   476012 non-null  float64
 5   cloud_cover                   476012 non-null  float64
dtypes: float64(4), int64(1), object(1)
memory usage: 21.8+ MB
None

Information of Solar df
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4081774 entries, 0 to 4081773
Data columns (total 8 columns):
 #   Column      Dtype
---  ------      -----
 0   asset_id    int64
 1   read_at     object
 2   ac_power    float64
 3   ac_voltage  float64
 4   ac_current  float64
 5   dc_power    float64
 6   dc_voltage  float64
 7   dc_current  float64
dtypes: float64(6), int64(1), object(1)
memory usage: 249.1+ MB
None

Information of Wind df
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8367759 entries, 0 to 8367758
Data columns (total 8 columns):
 #   Column                Dtype
---  ------                -----
 0   asset_id              int64
 1   read_at               object
 2   wind_speed            float64
 3   wind_direction        float64
 4   power_average         float64
 5   rotation_average      float64
 6   exterior_temperature  float64
 7   nacelle_temperature   float64
dtypes: float64(6), int64(1), object(1)
memory usage: 510.7+ MB
None

In [5]:
for key, value in dfs_dict.items():
    print(f"NAs count for {key}")
    print(value.isna().sum(), "\n")

NAs count for Satellite
satellite_id                    0
read_at                         0
global_tilted_irradiance        0
global_horizontal_irradiance    0
temperature                     0
cloud_cover                     0
dtype: int64

NAs count for Solar
asset_id          0
read_at           0
ac_power          0
ac_voltage    99722
ac_current    99722
dc_power          0
dc_voltage        0
dc_current        0
dtype: int64

NAs count for Wind
asset_id                0
read_at                 0
wind_speed              0
wind_direction          0
power_average           0
rotation_average        0
exterior_temperature    1
nacelle_temperature     1
dtype: int64

In [6]:
df_solar_only_na = df_solar[df_solar["ac_voltage"].isna()]
print(df_solar_only_na)
#df_solar_only_na.to_csv("outputs/solar_only_nas.csv")

         asset_id              read_at  ac_power  ac_voltage  ac_current  \
3109038       411  2022-01-01 07:40:00       0.0         NaN         NaN
3109039       411  2022-01-01 07:50:00       0.0         NaN         NaN
3109040       411  2022-01-01 08:00:00       0.0         NaN         NaN
3109041       411  2022-01-01 08:10:00     259.0         NaN         NaN
3109042       411  2022-01-01 08:20:00     531.0         NaN         NaN
...           ...                  ...       ...         ...         ...
3208755       412  2024-01-09 13:20:00    1857.0         NaN         NaN
3208756       412  2024-01-09 13:30:00    2015.0         NaN         NaN
3208757       412  2024-01-09 13:40:00    2114.0         NaN         NaN
3208758       412  2024-01-09 13:50:00    1459.0         NaN         NaN
3208759       412  2024-01-09 14:00:00    4352.0         NaN         NaN

         dc_power  dc_voltage  dc_current
3109038       0.0      482.74       0.000
3109039       0.0      519.87       0.000
3109040       0.0      527.25       0.000
3109041     188.0      456.33       0.419
3109042     349.0      479.84       0.733
...           ...         ...         ...
3208755    1877.0      518.82       3.621
3208756    2047.0      537.71       3.808
3208757    2136.0      543.88       3.929
3208758    1465.0      511.86       2.864
3208759    4438.0      521.15       8.518

[99722 rows x 8 columns]

it's possible to see that the asset number 411 dont have values for the columns ac_voltage and ac_current

In [38]:
df_solar_only_not_na = df_solar[~df_solar["ac_voltage"].isna()]
print(f"Median: {df_solar_only_not_na['ac_current'].median()}")
print(f"Average: {df_solar_only_not_na['ac_current'].mean()}")

Median: 4.679
Average: 11.763000043458105